name: Android CI

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: Build with CI build script
      run: |
           $ANDROID_NDK_LATEST_HOME/ndk-build -j4 APP_PLATFORM=android-24 APP_BUILD_SCRIPT=./Android.mk NDK_APPLICATION_MK=./jni/Application.mk NDK_PROJECT_PATH=.

    - name: Upload build output
      uses: actions/upload-artifact@main
      with:
        name: holy
        path: libs
